name: Build & Push binaries

permissions:
  contents: write

on:
  pull_request:
  push:
      paths-ignore:
        - '.gitignore'
        - 'LICENSE'
        - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { runner: windows-latest, os: windows, arch: x64,    archive_ext: .zip }
        mode: [debug, releasedbg]

    runs-on: ${{ matrix.platform.runner }}

    steps:
    - name: Get current date as package key
      id: cache_key
      run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT
      shell: bash

    - name: "Set OUTPUT_FILE variable"
      run: echo "OUTPUT_FILE=${{ matrix.platform.os }}_${{ matrix.platform.arch }}_${{ matrix.mode }}${{ matrix.platform.archive_ext }}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Clone the whole repository to get correct tags and branches

    # Install xmake
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@test
        actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

    # Update xmake repository (in order to have the file that will be cached)
    - name: Update xmake repository
      run: xmake repo --update

    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.platform.arch }} --mode=${{ matrix.mode }} --yes --policies=package.precompiled:n
